### ISSUE TITLE
Refactor the default backend into a module

### ISSUE THREAD

**Issue by pepeiborra** [ndmitchell/debug#33]
I would like to reorganise the module structure to:
- move the trace recording (`getDebugTrace`) from Debug.Record and the TH bits from Debug into a new module Debug.Backend.Default
- Debug.Record gets renamed to Debug.Types
- Debug simply reexports Debug.Backend.Default

**Comment by ndmitchell** [comment]
Seems reasonable. I think the important thing is that we have a small number of modules, and that the way to annotate a module remains somewhat stable (a change now is fine, but we want that to be the last change, ideally).

I'm also wondering if it should be `Debug.Trace.Variables` and `Debug.Trace.Hoed` as the modules instead of `Debug` alone, so there is more symmetry?

**Comment by pepeiborra** [comment]
We would end up with 4 modules:  
 

 
- Debug  
 
- Debug.Types
 
- A module for the Variables Backend  
 
- A module for the Hoed Backend  
 

 
Imo we should keep the Debug module and ensure it is the only import required for 90% of use cases.
 
 
>  
>  
>    
>    
>

**Comment by ndmitchell** [comment]
Is `Debug.Types` the right name, as it will also be able to deal with manipulating a trace. It feels like `Debug.TracedFileFormat` or similar is the right name (not exactly that, but that kind of feeling).
